name: Build and upload artifacts

on:
    workflow_call:

jobs:
    build_and_upload_artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up 'node'
              uses: actions/setup-node@v6

            - name: Set up 'pnpm'
              uses: pnpm/action-setup@v6
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm run build

            - name: Upload artifact
              id: upload_artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: dist

            - name: Echo artifact ID
              run: echo ${{ steps.upload_artifact.outputs.artifact_id }}
