name: Build and upload artifact

on:
    workflow_call:
        outputs:
            artifact_url:
                description: "Artifact URL"
                value: ${{ jobs.build_and_upload_artifact.artifact_url }}

jobs:
    build_and_upload_artifact:
        runs-on: ubuntu-latest
        outputs:
            artifact_url: ${{ steps.upload_artifact.outputs.artifact-url }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up 'node'
              uses: actions/setup-node@v6
              with:
                  node-version: latest

            - name: Set up 'pnpm'
              uses: pnpm/action-setup@v6
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm run build

            - name: Upload artifact
              id: upload_artifact
              uses: actions/upload-artifact@v7
              with:
                  name: ping_me
                  path: dist
                  if-no-files-found: error

            - name: Echo artifact ID
              run: echo ${{ steps.upload_artifact.outputs.artifact-id }}

            - name: Echo artifact URL
              run: echo ${{ steps.upload_artifact.outputs.artifact-url }}
